name: Main
on: [push, pull_request]
permissions:
  contents: read
jobs:
  lint-contracts:
    name: Lint Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm install -g solhint
          solhint -f table src/**/*.sol
  test-contracts:
    name: Test Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: build
        run: forge build
      - name: test
        run: forge test -vvv
  test-contracts-security:
    name: Test Contracts Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install slither
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
          git clone https://github.com/crytic/slither.git
          pushd slither
          python3 setup.py install
          popd
      - name: run slither
        run: |
          slither . --sarif slither.results.sarif
      - name: upload slither report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: njsscan.results.sarif
  test-bindings:
    name: Test Bindings
    runs-on: ubuntu-latest
    env:
      OPENLOTTO_MNEMONIC: 'test test test test test test test test test test test junk'
      OPENLOTTO_NUM_LOTTERIES: 0
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly   
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: test
        run: |
          forge build --extra-output-files abi
          npm install
          npm test
  test-bindings-security:
    name: Test Bindings Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: run njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output njsscan.results.sarif || true'
      - name: upload njsscan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: njsscan.results.sarif
  release-bindings:
    name: Release Bindings
    needs: [test-bindings]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: build
        run: |
          forge build --extra-output-files abi
          npm install
          npm pack
      - uses: softprops/action-gh-release@v1
        with:
          files: openlotto-bindings-*.tgz
