name: Security
on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '27 16 * * 2'
jobs:
  test-contracts-security:
    name: Test Contracts Security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dcarbone/install-jq-action@v2.1.0
      - uses: crytic/slither-action@v0.3.2
        with:
          slither-version: e3346c0dcd6fb8960ccbee8d153e99a0892b2925
          target: '.'
          fail-on: none
          sarif: slither.results.full.sarif
          slither-args: --exclude-dependencies --exclude-optimization --exclude-informational --exclude-low --exclude-medium
      - run: |
          jq '.runs[].results |= map(select(.locations[].physicalLocation.artifactLocation.uri | startswith("src")))' slither.results.full.sarif > slither.results.sarif
      - name: upload slither report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: slither.results.sarif
  test-bindings-security:
    name: Test Bindings Security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: run njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output njsscan.results.sarif || true'
      - name: upload njsscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: njsscan.results.sarif